In [1]:
from transformers import pipeline

https://huggingface.co/dslim/bert-large-NER

- O	Outside of a named entity
- B-MISC	Beginning of a miscellaneous entity right after another miscellaneous entity
- I-MISC	Miscellaneous entity
- B-PER	Beginning of a person’s name right after another person’s name
- I-PER	Person’s name
- B-ORG	Beginning of an organization right after another organization
- I-ORG	organization
- B-LOC	Beginning of a location right after another location
- I-LOC	Location

In [2]:
ner_pipeline = pipeline("ner", model="dslim/bert-large-NER")

ner_pipeline

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:86: UserWarning: 
Access to the secret `HF_TOKEN` has not been granted on this notebook.
You will not be requested again.
Please restart the session if you want to be prompted again.
  warnings.warn(


config.json:   0%|          | 0.00/1.45k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dslim/bert-large-NER were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/40.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cpu


In [3]:
text = "Jane will be at the the United Nations General Assembly will be held in New York City on September 25, 2025."

print(text)

ner_pipeline(text)

Jane will be at the the United Nations General Assembly will be held in New York City on September 25, 2024.


[{'entity': 'B-PER',
  'score': np.float32(0.99825007),
  'index': 1,
  'word': 'Jane',
  'start': 0,
  'end': 4},
 {'entity': 'B-ORG',
  'score': np.float32(0.9930275),
  'index': 7,
  'word': 'United',
  'start': 24,
  'end': 30},
 {'entity': 'I-ORG',
  'score': np.float32(0.9975158),
  'index': 8,
  'word': 'Nations',
  'start': 31,
  'end': 38},
 {'entity': 'I-ORG',
  'score': np.float32(0.9965065),
  'index': 9,
  'word': 'General',
  'start': 39,
  'end': 46},
 {'entity': 'I-ORG',
  'score': np.float32(0.9975141),
  'index': 10,
  'word': 'Assembly',
  'start': 47,
  'end': 55},
 {'entity': 'B-LOC',
  'score': np.float32(0.9990243),
  'index': 15,
  'word': 'New',
  'start': 72,
  'end': 75},
 {'entity': 'I-LOC',
  'score': np.float32(0.99946517),
  'index': 16,
  'word': 'York',
  'start': 76,
  'end': 80},
 {'entity': 'I-LOC',
  'score': np.float32(0.99955016),
  'index': 17,
  'word': 'City',
  'start': 81,
  'end': 85}]

aggregation_strategy is used to group the entities in the predictions. It will group "New York City" together

https://huggingface.co/docs/transformers/main/en/main_classes/pipelines#transformers.TokenClassificationPipeline

In [4]:
text = "Jane will be at the the United Nations General Assembly will be held in New York City on September 25, 2024."

print(text)

ner_pipeline(text, aggregation_strategy="simple")

Jane will be at the the United Nations General Assembly will be held in New York City on September 25, 2024.


[{'entity_group': 'PER',
  'score': np.float32(0.99825007),
  'word': 'Jane',
  'start': 0,
  'end': 4},
 {'entity_group': 'ORG',
  'score': np.float32(0.99614096),
  'word': 'United Nations General Assembly',
  'start': 24,
  'end': 55},
 {'entity_group': 'LOC',
  'score': np.float32(0.9993465),
  'word': 'New York City',
  'start': 72,
  'end': 85}]

In [5]:
text =  "Angela Merkel visited Tokyo for a diplomatic meeting."

ner_pipeline(text)

[{'entity': 'B-PER',
  'score': np.float32(0.99811435),
  'index': 1,
  'word': 'Angela',
  'start': 0,
  'end': 6},
 {'entity': 'I-PER',
  'score': np.float32(0.9969157),
  'index': 2,
  'word': 'Me',
  'start': 7,
  'end': 9},
 {'entity': 'I-PER',
  'score': np.float32(0.9168182),
  'index': 3,
  'word': '##rk',
  'start': 9,
  'end': 11},
 {'entity': 'I-PER',
  'score': np.float32(0.9313463),
  'index': 4,
  'word': '##el',
  'start': 11,
  'end': 13},
 {'entity': 'B-LOC',
  'score': np.float32(0.99942386),
  'index': 6,
  'word': 'Tokyo',
  'start': 22,
  'end': 27}]

In [6]:
text =  "Angela Merkel visited Tokyo for a diplomatic meeting."

ner_pipeline(text, aggregation_strategy="simple")

[{'entity_group': 'PER',
  'score': np.float32(0.9607986),
  'word': 'Angela Merkel',
  'start': 0,
  'end': 13},
 {'entity_group': 'LOC',
  'score': np.float32(0.99942386),
  'word': 'Tokyo',
  'start': 22,
  'end': 27}]

In [7]:
text = "Microsoft Corporation, founded by Bill Gates, is a leading technology company."

ner_pipeline(text, aggregation_strategy="simple")

[{'entity_group': 'ORG',
  'score': np.float32(0.99924994),
  'word': 'Microsoft Corporation',
  'start': 0,
  'end': 21},
 {'entity_group': 'PER',
  'score': np.float32(0.99708855),
  'word': 'Bill Gates',
  'start': 34,
  'end': 44}]

In [8]:
texts = [
    "The Eiffel Tower, an iconic symbol of Paris and French culture, drawing millions of visitors who come to admire its iron lattice structure and breathtaking views of the city.",
    "Mount Everest is the highest mountain in the world, towering over the Himalayas and straddling the border between Nepal and Tibet."
]

print(texts)

ner_pipeline(texts, aggregation_strategy="simple")

['The Eiffel Tower, an iconic symbol of Paris and French culture, drawing millions of visitors who come to admire its iron lattice structure and breathtaking views of the city.', 'Mount Everest is the highest mountain in the world, towering over the Himalayas and straddling the border between Nepal and Tibet.']


[[{'entity_group': 'LOC',
   'score': np.float32(0.87292373),
   'word': 'Eiffel Tower',
   'start': 4,
   'end': 16},
  {'entity_group': 'LOC',
   'score': np.float32(0.9992901),
   'word': 'Paris',
   'start': 38,
   'end': 43},
  {'entity_group': 'MISC',
   'score': np.float32(0.99943286),
   'word': 'French',
   'start': 48,
   'end': 54}],
 [{'entity_group': 'LOC',
   'score': np.float32(0.49357674),
   'word': 'Mount',
   'start': 0,
   'end': 5},
  {'entity_group': 'MISC',
   'score': np.float32(0.32996774),
   'word': 'Everest',
   'start': 6,
   'end': 13},
  {'entity_group': 'LOC',
   'score': np.float32(0.94761103),
   'word': 'Himalayas',
   'start': 70,
   'end': 79},
  {'entity_group': 'LOC',
   'score': np.float32(0.99965),
   'word': 'Nepal',
   'start': 114,
   'end': 119},
  {'entity_group': 'LOC',
   'score': np.float32(0.9996458),
   'word': 'Tibet',
   'start': 124,
   'end': 129}]]

In [9]:
ner_results = ner_pipeline(texts, aggregation_strategy="simple")

for idx, (text, result) in enumerate(zip(texts, ner_results), 1):
    print(f"\nText {idx}: {text}")

    if result and isinstance(result[0], dict):
        print("Entities:")
        for entity in result:
            for key, value in entity.items():
                print(f"  - {key}: {value}")


Text 1: The Eiffel Tower, an iconic symbol of Paris and French culture, drawing millions of visitors who come to admire its iron lattice structure and breathtaking views of the city.
Entities:
  - entity_group: LOC
  - score: 0.872923731803894
  - word: Eiffel Tower
  - start: 4
  - end: 16
  - entity_group: LOC
  - score: 0.9992901086807251
  - word: Paris
  - start: 38
  - end: 43
  - entity_group: MISC
  - score: 0.9994328618049622
  - word: French
  - start: 48
  - end: 54

Text 2: Mount Everest is the highest mountain in the world, towering over the Himalayas and straddling the border between Nepal and Tibet.
Entities:
  - entity_group: LOC
  - score: 0.4935767352581024
  - word: Mount
  - start: 0
  - end: 5
  - entity_group: MISC
  - score: 0.329967737197876
  - word: Everest
  - start: 6
  - end: 13
  - entity_group: LOC
  - score: 0.9476110339164734
  - word: Himalayas
  - start: 70
  - end: 79
  - entity_group: LOC
  - score: 0.9996500015258789
  - word: Nepal
  - start: 114

https://huggingface.co/FacebookAI/xlm-roberta-large-finetuned-conll03-english

In [10]:
import tensorflow as tf

from transformers import TFBertForTokenClassification, BertTokenizer, AutoTokenizer,TFAutoModelForTokenClassification

In [11]:
FB_MODEL = "xlm-roberta-large-finetuned-conll03-english"

FB_MODEL

'xlm-roberta-large-finetuned-conll03-english'

In [12]:
tokenizer = AutoTokenizer.from_pretrained(FB_MODEL)

tokenizer

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/852 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

XLMRobertaTokenizerFast(name_or_path='xlm-roberta-large-finetuned-conll03-english', vocab_size=250002, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	250001: AddedToken("<mask>", rstrip=False, lstrip=True, single_word=False, normalized=False, special=True),
}
)

The original model was trained using PyTorch and we convert it to TensorFlow using from_pt = True

In [13]:
model = TFAutoModelForTokenClassification.from_pretrained(
    FB_MODEL, from_pt=True)

model

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


pytorch_model.bin:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFXLMRobertaForTokenClassification.

All the weights of TFXLMRobertaForTokenClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLMRobertaForTokenClassification for predictions without further training.


In [15]:
text = """
The Grand Canyon is a vast natural wonder located in Arizona, USA. It was shaped by the Colorado River over millions of years,
creating stunning geological formations and rich biodiversity. The Grand Canyon National Park is managed by the National Park Service, and
renowned geologist John Wesley Powell was among the first to document the canyon's remarkable features in the late 19th century.
"""

text

"\nThe Grand Canyon is a vast natural wonder located in Arizona, USA. It was shaped by the Colorado River over millions of years,\ncreating stunning geological formations and rich biodiversity. The Grand Canyon National Park is managed by the National Park Service, and\nrenowned geologist John Wesley Powell was among the first to document the canyon's remarkable features in the late 19th century.\n"

In [16]:
tokens = tokenizer.encode_plus(text, return_tensors="tf")

tokens

{'input_ids': <tf.Tensor: shape=(1, 87), dtype=int32, numpy=
array([[     0,    581,  12801, 193266,     83,     10,  18410,   6083,
         32195, 105866,     23, 157487,      4,   4602,      5,   1650,
           509, 115700,     71,    390,     70, 156256,  32547,    645,
         43077,    111,   5369,      4, 105233, 228008,    700, 109622,
         27643,      7,    136,  98870,      6, 179174,    939,      5,
           581,  12801, 193266,   9907,   5227,     83, 145755,    390,
            70,   9907,   5227,  12349,      4,    136,  10670, 157272,
        153443,    271,   4939,   1401,      7,   4293,    663,  19256,
           509,  54940,     70,   5117,     47,  12937,     70,    831,
          9480,     25,      7,    456,  10015,   2886,  66139,     23,
            70,  72399,    953,    927, 142642,      5,      2]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 87), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [17]:
outputs = model(tokens)

outputs

TFTokenClassifierOutput(loss=None, logits=<tf.Tensor: shape=(1, 87, 8), dtype=float32, numpy=
array([[[-3.2883832 , -3.2258973 , -2.5896187 , -0.4173886 ,
         -1.4544038 , -0.6070593 , -0.7492139 , 11.739959  ],
        [-1.6348858 , -2.9722097 , -2.880501  ,  0.777457  ,
         -3.112695  , -1.6158779 , -1.1264905 , 12.714818  ],
        [ 0.5859135 , -1.9557753 , -2.576701  , 11.015005  ,
         -2.905007  , -0.81120867,  0.45704955, -2.2136726 ],
        [ 0.27086467, -2.01276   , -2.4923398 , 10.810306  ,
         -2.5471787 , -0.8432262 ,  0.3954356 , -2.2232084 ],
        [-1.8159785 , -2.5435984 , -2.0072765 , -1.2692454 ,
         -3.3229637 , -1.5441854 , -1.4769108 , 14.63477   ],
        [-2.2331054 , -2.5056267 , -2.123025  , -1.4289899 ,
         -3.1375105 , -1.5646011 , -1.325516  , 14.522811  ],
        [-2.037135  , -2.5569558 , -2.2519836 , -1.4698651 ,
         -3.2840204 , -1.4632261 , -1.2493161 , 14.617425  ],
        [-2.0075538 , -2.4301817 , -2.1465569

##### obtain predicted labels by finding the index with the highest probability

In [18]:
predicted_labels = tf.argmax(outputs.logits, axis=2).numpy()

predicted_labels

array([[7, 7, 3, 3, 7, 7, 7, 7, 7, 7, 7, 3, 7, 3, 7, 7, 7, 7, 7, 7, 7, 3,
        3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 3,
        3, 7, 7, 7, 7, 5, 5, 5, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

##### converting back

In [19]:
model.config.id2label

{0: 'B-LOC',
 1: 'B-MISC',
 2: 'B-ORG',
 3: 'I-LOC',
 4: 'I-MISC',
 5: 'I-ORG',
 6: 'I-PER',
 7: 'O'}

In [20]:
predicted_tokens = tokenizer.convert_ids_to_tokens(tokens["input_ids"][0])

predicted_tokens

['<s>',
 '▁The',
 '▁Grand',
 '▁Canyon',
 '▁is',
 '▁a',
 '▁vast',
 '▁natural',
 '▁wonder',
 '▁located',
 '▁in',
 '▁Arizona',
 ',',
 '▁USA',
 '.',
 '▁It',
 '▁was',
 '▁shape',
 'd',
 '▁by',
 '▁the',
 '▁Colorado',
 '▁River',
 '▁over',
 '▁millions',
 '▁of',
 '▁years',
 ',',
 '▁creating',
 '▁stunning',
 '▁ge',
 'ological',
 '▁formation',
 's',
 '▁and',
 '▁rich',
 '▁',
 'biodiversi',
 'ty',
 '.',
 '▁The',
 '▁Grand',
 '▁Canyon',
 '▁National',
 '▁Park',
 '▁is',
 '▁managed',
 '▁by',
 '▁the',
 '▁National',
 '▁Park',
 '▁Service',
 ',',
 '▁and',
 '▁ren',
 'owned',
 '▁geologi',
 'st',
 '▁John',
 '▁We',
 's',
 'ley',
 '▁Po',
 'well',
 '▁was',
 '▁among',
 '▁the',
 '▁first',
 '▁to',
 '▁document',
 '▁the',
 '▁can',
 'yon',
 "'",
 's',
 '▁re',
 'mark',
 'able',
 '▁features',
 '▁in',
 '▁the',
 '▁late',
 '▁19',
 'th',
 '▁century',
 '.',
 '</s>']

In [21]:
for token, label in zip(predicted_tokens, predicted_labels[0]):
    print(f"{token} - {model.config.id2label[label]}")

<s> - O
▁The - O
▁Grand - I-LOC
▁Canyon - I-LOC
▁is - O
▁a - O
▁vast - O
▁natural - O
▁wonder - O
▁located - O
▁in - O
▁Arizona - I-LOC
, - O
▁USA - I-LOC
. - O
▁It - O
▁was - O
▁shape - O
d - O
▁by - O
▁the - O
▁Colorado - I-LOC
▁River - I-LOC
▁over - O
▁millions - O
▁of - O
▁years - O
, - O
▁creating - O
▁stunning - O
▁ge - O
ological - O
▁formation - O
s - O
▁and - O
▁rich - O
▁ - O
biodiversi - O
ty - O
. - O
▁The - O
▁Grand - I-LOC
▁Canyon - I-LOC
▁National - I-LOC
▁Park - I-LOC
▁is - O
▁managed - O
▁by - O
▁the - O
▁National - I-ORG
▁Park - I-ORG
▁Service - I-ORG
, - O
▁and - O
▁ren - O
owned - O
▁geologi - O
st - O
▁John - I-PER
▁We - I-PER
s - I-PER
ley - I-PER
▁Po - I-PER
well - I-PER
▁was - O
▁among - O
▁the - O
▁first - O
▁to - O
▁document - O
▁the - O
▁can - O
yon - O
' - O
s - O
▁re - O
mark - O
able - O
▁features - O
▁in - O
▁the - O
▁late - O
▁19 - O
th - O
▁century - O
. - O
</s> - O


##### removing all the unnessary _, O and parsing it properly for better understanding

In [22]:
result_dict = {}

current_entity = ""
current_label = None

for token, label_id in zip(predicted_tokens, predicted_labels[0]):
    label = model.config.id2label[label_id]

    # Split I-PER, B-PER etc into two parts and access the second part
    # For O or outside just have the label O
    entity_type = label.split('-', 1)[1] if '-' in label else 'O'

    if entity_type != 'O':
        # For XLM-Roberta, subword tokens are prefixed with '▁' (U+2581)
        # Anything with '_' is the start of a word
        if token.startswith("▁"):
            if current_entity:
                result_dict[current_entity] = current_label
            current_entity = token[1:]  # Remove the '▁' at the start
        else:
            current_entity += token  # Append subword without space
        current_label = entity_type
    elif current_entity:
        result_dict[current_entity] = current_label
        current_entity = ""
        current_label = None

# Handle the last entity if it exists
if current_entity:
    result_dict[current_entity] = current_label

print(result_dict)

{'Grand': 'LOC', 'Canyon': 'LOC', 'Arizona': 'LOC', 'USA': 'LOC', 'Colorado': 'LOC', 'River': 'LOC', 'National': 'ORG', 'Park': 'ORG', 'Service': 'ORG', 'John': 'PER', 'Wesley': 'PER', 'Powell': 'PER'}


In [23]:
for entity, label in result_dict.items():
    print(f"{entity} - {label}")

Grand - LOC
Canyon - LOC
Arizona - LOC
USA - LOC
Colorado - LOC
River - LOC
National - ORG
Park - ORG
Service - ORG
John - PER
Wesley - PER
Powell - PER
